In [1]:
import cupy as cp

In [2]:
data = [1, 2, 3, 4, 5]

In [4]:
cp.array(data)

array([1, 2, 3, 4, 5])

#### 元素全為0的矩陣

In [6]:
cp.zeros(3)

array([0., 0., 0.])

#### 元素全為1的矩陣

In [7]:
cp.ones(3)

array([1., 1., 1.])

#### 在 [0, 1) 範圍內均勻分佈的隨機數

In [8]:
cp.random.rand(2, 2)

array([[0.91249194, 0.64095525],
       [0.34076416, 0.91113129]])

#### 服從標準正態分佈 (均值為 0，標準差為 1) 的隨機數。

In [9]:
cp.random.randn(2, 2)

array([[-3.41077867, -2.411171  ],
       [-0.30869584, -1.20866971]])

#### exponential function

In [17]:
cp.exp(1)

array(2.71828183)

#### log function

In [11]:
cp.log(1)

array(0.)

#### trigonometric functions

In [14]:
cp.sin(1)

array(0.54030231)

In [15]:
cp.cos(1)

array(0.54030231)

In [16]:
cp.tan(1)

array(1.55740772)

#### 內積

In [ ]:
#cp.dot()

In [ ]:
#cp.inner()

#### transpose (轉置)

In [ ]:
cp.transpose()

#### 矩陣相加

In [ ]:
cp.add()

#### 矩陣相乘

In [ ]:
cp.matmul()

#### 求反矩陣

In [ ]:
cp.linalg.inv()

#### eigen value 求特徵值

In [ ]:
cp.linalg.eig()

In [ ]:
cp.linalg.cholesky()

#### 傅立葉轉換

In [ ]:
cp.fft.fft()